generate:
  - types
  - client
accessModifier: internal
namingStrategy: idiomatic
filter:
  operations:
    - accountsGetMe
    - activitiesCreate
    - activitiesGetTimeline
    - activitiesGetLabelTimeline
    - activitiesGetSegmentLabelState
    - authExchangeToken
    - devicesCreate
