// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// 현재 계정 조회
    ///
    /// Bearer 액세스 토큰으로 인증된 Mosemo 계정 정보를 조회합니다.
    ///
    /// - Remark: HTTP `GET /api/v1/accounts/me`.
    /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(get_me_api_v1_accounts_me_get)`.
    func getMeApiV1AccountsMeGet(_ input: Operations.GetMeApiV1AccountsMeGet.Input) async throws -> Operations.GetMeApiV1AccountsMeGet.Output
    /// 액세스 토큰 발급
    ///
    /// Kakao 로그인 callback에서 발급한 일회용 인증 코드와 PKCE code verifier를 검증한 뒤 Mosemo 액세스 토큰을 발급합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/auth/token`.
    /// - Remark: Generated from `#/paths//api/v1/auth/token/post(exchange_token_api_v1_auth_token_post)`.
    func exchangeTokenApiV1AuthTokenPost(_ input: Operations.ExchangeTokenApiV1AuthTokenPost.Input) async throws -> Operations.ExchangeTokenApiV1AuthTokenPost.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// 현재 계정 조회
    ///
    /// Bearer 액세스 토큰으로 인증된 Mosemo 계정 정보를 조회합니다.
    ///
    /// - Remark: HTTP `GET /api/v1/accounts/me`.
    /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(get_me_api_v1_accounts_me_get)`.
    internal func getMeApiV1AccountsMeGet(headers: Operations.GetMeApiV1AccountsMeGet.Input.Headers = .init()) async throws -> Operations.GetMeApiV1AccountsMeGet.Output {
        try await getMeApiV1AccountsMeGet(Operations.GetMeApiV1AccountsMeGet.Input(headers: headers))
    }
    /// 액세스 토큰 발급
    ///
    /// Kakao 로그인 callback에서 발급한 일회용 인증 코드와 PKCE code verifier를 검증한 뒤 Mosemo 액세스 토큰을 발급합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/auth/token`.
    /// - Remark: Generated from `#/paths//api/v1/auth/token/post(exchange_token_api_v1_auth_token_post)`.
    internal func exchangeTokenApiV1AuthTokenPost(
        headers: Operations.ExchangeTokenApiV1AuthTokenPost.Input.Headers = .init(),
        body: Operations.ExchangeTokenApiV1AuthTokenPost.Input.Body
    ) async throws -> Operations.ExchangeTokenApiV1AuthTokenPost.Output {
        try await exchangeTokenApiV1AuthTokenPost(Operations.ExchangeTokenApiV1AuthTokenPost.Input(
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {}

/// Types generated from the components section of the OpenAPI document.
internal enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {
        /// - Remark: Generated from `#/components/schemas/AccountProvider`.
        internal enum AccountProvider: String, Codable, Hashable, Sendable, CaseIterable {
            case kakao = "KAKAO"
        }
        /// 현재 인증된 Mosemo 계정의 공개 정보입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/AccountResponse`.
        internal struct AccountResponse: Codable, Hashable, Sendable {
            /// Mosemo 계정의 고유 식별자입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/account_id`.
            internal var accountId: Swift.String
            /// 계정이 생성된 시각입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/created_at`.
            internal var createdAt: Foundation.Date
            /// 외부 인증 제공자를 통해 마지막으로 인증한 시각입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/last_authenticated_at`.
            internal var lastAuthenticatedAt: Foundation.Date
            /// 계정 인증에 사용한 외부 인증 제공자입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/provider`.
            internal var provider: Components.Schemas.AccountProvider
            /// Creates a new `AccountResponse`.
            ///
            /// - Parameters:
            ///   - accountId: Mosemo 계정의 고유 식별자입니다.
            ///   - createdAt: 계정이 생성된 시각입니다.
            ///   - lastAuthenticatedAt: 외부 인증 제공자를 통해 마지막으로 인증한 시각입니다.
            ///   - provider: 계정 인증에 사용한 외부 인증 제공자입니다.
            internal init(
                accountId: Swift.String,
                createdAt: Foundation.Date,
                lastAuthenticatedAt: Foundation.Date,
                provider: Components.Schemas.AccountProvider
            ) {
                self.accountId = accountId
                self.createdAt = createdAt
                self.lastAuthenticatedAt = lastAuthenticatedAt
                self.provider = provider
            }
            internal enum CodingKeys: String, CodingKey {
                case accountId = "account_id"
                case createdAt = "created_at"
                case lastAuthenticatedAt = "last_authenticated_at"
                case provider
            }
        }
        /// Mosemo API가 통제된 오류를 반환할 때 사용하는 응답입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/ApiErrorResponse`.
        internal struct ApiErrorResponse: Codable, Hashable, Sendable {
            /// 클라이언트에 공개하는 오류 메시지입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ApiErrorResponse/detail`.
            internal var detail: Swift.String
            /// Creates a new `ApiErrorResponse`.
            ///
            /// - Parameters:
            ///   - detail: 클라이언트에 공개하는 오류 메시지입니다.
            internal init(detail: Swift.String) {
                self.detail = detail
            }
            internal enum CodingKeys: String, CodingKey {
                case detail
            }
        }
        /// FastAPI가 요청 입력값 검증 실패 시 반환하는 응답입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/RequestValidationErrorResponse`.
        internal struct RequestValidationErrorResponse: Codable, Hashable, Sendable {
            /// 요청에서 발견된 입력값 검증 오류 목록입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/RequestValidationErrorResponse/detail`.
            internal var detail: [Components.Schemas.ValidationErrorDetail]
            /// Creates a new `RequestValidationErrorResponse`.
            ///
            /// - Parameters:
            ///   - detail: 요청에서 발견된 입력값 검증 오류 목록입니다.
            internal init(detail: [Components.Schemas.ValidationErrorDetail]) {
                self.detail = detail
            }
            internal enum CodingKeys: String, CodingKey {
                case detail
            }
        }
        /// 일회용 인증 코드를 Mosemo 액세스 토큰으로 교환하는 요청입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/TokenRequest`.
        internal struct TokenRequest: Codable, Hashable, Sendable {
            /// Kakao 로그인 callback에서 macOS 앱으로 전달한 일회용 인증 코드입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/code`.
            internal var code: Swift.String
            /// 로그인 요청의 code_challenge를 생성할 때 사용한 43~128자의 PKCE code verifier입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/code_verifier`.
            internal var codeVerifier: Swift.String
            /// 토큰 발급 방식이며 authorization_code만 허용합니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/grant_type`.
            internal enum GrantTypePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case authorizationCode = "authorization_code"
            }
            /// 토큰 발급 방식이며 authorization_code만 허용합니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/grant_type`.
            internal var grantType: Components.Schemas.TokenRequest.GrantTypePayload
            /// Creates a new `TokenRequest`.
            ///
            /// - Parameters:
            ///   - code: Kakao 로그인 callback에서 macOS 앱으로 전달한 일회용 인증 코드입니다.
            ///   - codeVerifier: 로그인 요청의 code_challenge를 생성할 때 사용한 43~128자의 PKCE code verifier입니다.
            ///   - grantType: 토큰 발급 방식이며 authorization_code만 허용합니다.
            internal init(
                code: Swift.String,
                codeVerifier: Swift.String,
                grantType: Components.Schemas.TokenRequest.GrantTypePayload
            ) {
                self.code = code
                self.codeVerifier = codeVerifier
                self.grantType = grantType
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case codeVerifier = "code_verifier"
                case grantType = "grant_type"
            }
        }
        /// Mosemo API 인증에 사용하는 액세스 토큰 응답입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/TokenResponse`.
        internal struct TokenResponse: Codable, Hashable, Sendable {
            /// Authorization 헤더에 사용할 Mosemo 액세스 토큰입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/access_token`.
            internal var accessToken: Swift.String
            /// 액세스 토큰이 발급 시점부터 유효한 시간(초)입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/expires_in`.
            internal var expiresIn: Swift.Int
            /// 액세스 토큰의 인증 방식이며 Bearer로 고정됩니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/token_type`.
            internal enum TokenTypePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case bearer = "Bearer"
            }
            /// 액세스 토큰의 인증 방식이며 Bearer로 고정됩니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/token_type`.
            internal var tokenType: Components.Schemas.TokenResponse.TokenTypePayload?
            /// Creates a new `TokenResponse`.
            ///
            /// - Parameters:
            ///   - accessToken: Authorization 헤더에 사용할 Mosemo 액세스 토큰입니다.
            ///   - expiresIn: 액세스 토큰이 발급 시점부터 유효한 시간(초)입니다.
            ///   - tokenType: 액세스 토큰의 인증 방식이며 Bearer로 고정됩니다.
            internal init(
                accessToken: Swift.String,
                expiresIn: Swift.Int,
                tokenType: Components.Schemas.TokenResponse.TokenTypePayload? = nil
            ) {
                self.accessToken = accessToken
                self.expiresIn = expiresIn
                self.tokenType = tokenType
            }
            internal enum CodingKeys: String, CodingKey {
                case accessToken = "access_token"
                case expiresIn = "expires_in"
                case tokenType = "token_type"
            }
        }
        /// 요청에서 발견된 개별 입력값 검증 오류입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail`.
        internal struct ValidationErrorDetail: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail/LocPayload`.
            internal struct LocPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail/LocPayload/value1`.
                internal var value1: Swift.String?
                /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail/LocPayload/value2`.
                internal var value2: Swift.Int?
                /// Creates a new `LocPayloadPayload`.
                ///
                /// - Parameters:
                ///   - value1:
                ///   - value2:
                internal init(
                    value1: Swift.String? = nil,
                    value2: Swift.Int? = nil
                ) {
                    self.value1 = value1
                    self.value2 = value2
                }
                internal init(from decoder: any Swift.Decoder) throws {
                    var errors: [any Swift.Error] = []
                    do {
                        self.value1 = try decoder.decodeFromSingleValueContainer()
                    } catch {
                        errors.append(error)
                    }
                    do {
                        self.value2 = try decoder.decodeFromSingleValueContainer()
                    } catch {
                        errors.append(error)
                    }
                    try Swift.DecodingError.verifyAtLeastOneSchemaIsNotNil(
                        [
                            self.value1,
                            self.value2
                        ],
                        type: Self.self,
                        codingPath: decoder.codingPath,
                        errors: errors
                    )
                }
                internal func encode(to encoder: any Swift.Encoder) throws {
                    try encoder.encodeFirstNonNilValueToSingleValueContainer([
                        self.value1,
                        self.value2
                    ])
                }
            }
            /// 오류가 발생한 요청 영역과 필드의 경로입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail/loc`.
            internal typealias LocPayload = [Components.Schemas.ValidationErrorDetail.LocPayloadPayload]
            /// 오류가 발생한 요청 영역과 필드의 경로입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail/loc`.
            internal var loc: Components.Schemas.ValidationErrorDetail.LocPayload
            /// 입력값이 유효하지 않은 이유입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail/msg`.
            internal var msg: Swift.String
            /// 검증 오류 유형을 식별하는 코드입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationErrorDetail/type`.
            internal var _type: Swift.String
            /// Creates a new `ValidationErrorDetail`.
            ///
            /// - Parameters:
            ///   - loc: 오류가 발생한 요청 영역과 필드의 경로입니다.
            ///   - msg: 입력값이 유효하지 않은 이유입니다.
            ///   - _type: 검증 오류 유형을 식별하는 코드입니다.
            internal init(
                loc: Components.Schemas.ValidationErrorDetail.LocPayload,
                msg: Swift.String,
                _type: Swift.String
            ) {
                self.loc = loc
                self.msg = msg
                self._type = _type
            }
            internal enum CodingKeys: String, CodingKey {
                case loc
                case msg
                case _type = "type"
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    internal enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    internal enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    internal enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    internal enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
internal enum Operations {
    /// 현재 계정 조회
    ///
    /// Bearer 액세스 토큰으로 인증된 Mosemo 계정 정보를 조회합니다.
    ///
    /// - Remark: HTTP `GET /api/v1/accounts/me`.
    /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(get_me_api_v1_accounts_me_get)`.
    internal enum GetMeApiV1AccountsMeGet {
        internal static let id: Swift.String = "get_me_api_v1_accounts_me_get"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/header`.
            internal struct Headers: Sendable, Hashable {
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetMeApiV1AccountsMeGet.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                internal init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetMeApiV1AccountsMeGet.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            internal var headers: Operations.GetMeApiV1AccountsMeGet.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            internal init(headers: Operations.GetMeApiV1AccountsMeGet.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.AccountResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.AccountResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.GetMeApiV1AccountsMeGet.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.GetMeApiV1AccountsMeGet.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// 현재 인증된 계정의 공개 정보입니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(get_me_api_v1_accounts_me_get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetMeApiV1AccountsMeGet.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.GetMeApiV1AccountsMeGet.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/headers/WWW-Authenticate`.
                    internal enum WWWAuthenticatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case bearer = "Bearer"
                    }
                    /// 클라이언트가 사용해야 하는 인증 방식입니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/headers/WWW-Authenticate`.
                    internal var wwwAuthenticate: Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized.Headers.WWWAuthenticatePayload?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - wwwAuthenticate: 클라이언트가 사용해야 하는 인증 방식입니다.
                    internal init(wwwAuthenticate: Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized.Headers.WWWAuthenticatePayload? = nil) {
                        self.wwwAuthenticate = wwwAuthenticate
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized.Headers
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/content/application\/json`.
                    case json(Components.Schemas.ApiErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ApiErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized.Body
                /// Creates a new `Unauthorized`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized.Headers = .init(),
                    body: Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// 액세스 토큰이 누락되었거나 유효하지 않거나 만료되었거나, 토큰의 계정이 존재하지 않습니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(get_me_api_v1_accounts_me_get)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.GetMeApiV1AccountsMeGet.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 액세스 토큰 발급
    ///
    /// Kakao 로그인 callback에서 발급한 일회용 인증 코드와 PKCE code verifier를 검증한 뒤 Mosemo 액세스 토큰을 발급합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/auth/token`.
    /// - Remark: Generated from `#/paths//api/v1/auth/token/post(exchange_token_api_v1_auth_token_post)`.
    internal enum ExchangeTokenApiV1AuthTokenPost {
        internal static let id: Swift.String = "exchange_token_api_v1_auth_token_post"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/header`.
            internal struct Headers: Sendable, Hashable {
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ExchangeTokenApiV1AuthTokenPost.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                internal init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ExchangeTokenApiV1AuthTokenPost.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            internal var headers: Operations.ExchangeTokenApiV1AuthTokenPost.Input.Headers
            /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.TokenRequest)
            }
            internal var body: Operations.ExchangeTokenApiV1AuthTokenPost.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            internal init(
                headers: Operations.ExchangeTokenApiV1AuthTokenPost.Input.Headers = .init(),
                body: Operations.ExchangeTokenApiV1AuthTokenPost.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Cache-Control`.
                    internal enum CacheControlPayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case noStore = "no-store"
                    }
                    /// 응답을 저장하지 않도록 no-store로 설정됩니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Cache-Control`.
                    internal var cacheControl: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Headers.CacheControlPayload?
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Pragma`.
                    internal enum PragmaPayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case noCache = "no-cache"
                    }
                    /// 이전 HTTP 캐시와의 호환을 위해 no-cache로 설정됩니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Pragma`.
                    internal var pragma: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Headers.PragmaPayload?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - cacheControl: 응답을 저장하지 않도록 no-store로 설정됩니다.
                    ///   - pragma: 이전 HTTP 캐시와의 호환을 위해 no-cache로 설정됩니다.
                    internal init(
                        cacheControl: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Headers.CacheControlPayload? = nil,
                        pragma: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Headers.PragmaPayload? = nil
                    ) {
                        self.cacheControl = cacheControl
                        self.pragma = pragma
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Headers
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.TokenResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.TokenResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Headers = .init(),
                    body: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Mosemo Bearer 액세스 토큰입니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(exchange_token_api_v1_auth_token_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.ExchangeTokenApiV1AuthTokenPost.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct BadRequest: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/400/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/400/content/application\/json`.
                    case json(Components.Schemas.ApiErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ApiErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.ExchangeTokenApiV1AuthTokenPost.Output.BadRequest.Body
                /// Creates a new `BadRequest`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.ExchangeTokenApiV1AuthTokenPost.Output.BadRequest.Body) {
                    self.body = body
                }
            }
            /// 일회용 인증 코드가 없거나 만료되었거나 이미 사용되었거나, PKCE code verifier가 유효하지 않습니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(exchange_token_api_v1_auth_token_post)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Operations.ExchangeTokenApiV1AuthTokenPost.Output.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            internal var badRequest: Operations.ExchangeTokenApiV1AuthTokenPost.Output.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            internal struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/422/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.RequestValidationErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.RequestValidationErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.ExchangeTokenApiV1AuthTokenPost.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.ExchangeTokenApiV1AuthTokenPost.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// 요청 본문의 필수 필드 또는 grant_type이 유효하지 않습니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(exchange_token_api_v1_auth_token_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.ExchangeTokenApiV1AuthTokenPost.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            internal var unprocessableContent: Operations.ExchangeTokenApiV1AuthTokenPost.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
