// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// 현재 계정 조회
    ///
    /// Bearer 액세스 토큰으로 인증된 Mosemo 계정 정보를 조회합니다.
    ///
    /// - Remark: HTTP `GET /api/v1/accounts/me`.
    /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)`.
    func accountsGetMe(_ input: Operations.AccountsGetMe.Input) async throws -> Operations.AccountsGetMe.Output
    /// 액세스 토큰 발급
    ///
    /// Kakao 로그인 callback에서 발급한 일회용 인증 코드와 PKCE code verifier를 검증한 뒤 Mosemo 액세스 토큰을 발급합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/auth/token`.
    /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)`.
    func authExchangeToken(_ input: Operations.AuthExchangeToken.Input) async throws -> Operations.AuthExchangeToken.Output
    /// Device 등록
    ///
    /// 인증된 계정에 앱 설치를 Device로 등록하고 서버가 발급한 식별자를 반환합니다. 같은 계정과 Idempotency-Key의 재시도는 최초 식별자를 반환합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/devices`.
    /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)`.
    func devicesCreate(_ input: Operations.DevicesCreate.Input) async throws -> Operations.DevicesCreate.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// 현재 계정 조회
    ///
    /// Bearer 액세스 토큰으로 인증된 Mosemo 계정 정보를 조회합니다.
    ///
    /// - Remark: HTTP `GET /api/v1/accounts/me`.
    /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)`.
    internal func accountsGetMe(headers: Operations.AccountsGetMe.Input.Headers = .init()) async throws -> Operations.AccountsGetMe.Output {
        try await accountsGetMe(Operations.AccountsGetMe.Input(headers: headers))
    }
    /// 액세스 토큰 발급
    ///
    /// Kakao 로그인 callback에서 발급한 일회용 인증 코드와 PKCE code verifier를 검증한 뒤 Mosemo 액세스 토큰을 발급합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/auth/token`.
    /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)`.
    internal func authExchangeToken(
        headers: Operations.AuthExchangeToken.Input.Headers = .init(),
        body: Operations.AuthExchangeToken.Input.Body
    ) async throws -> Operations.AuthExchangeToken.Output {
        try await authExchangeToken(Operations.AuthExchangeToken.Input(
            headers: headers,
            body: body
        ))
    }
    /// Device 등록
    ///
    /// 인증된 계정에 앱 설치를 Device로 등록하고 서버가 발급한 식별자를 반환합니다. 같은 계정과 Idempotency-Key의 재시도는 최초 식별자를 반환합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/devices`.
    /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)`.
    internal func devicesCreate(headers: Operations.DevicesCreate.Input.Headers) async throws -> Operations.DevicesCreate.Output {
        try await devicesCreate(Operations.DevicesCreate.Input(headers: headers))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {}

/// Types generated from the components section of the OpenAPI document.
internal enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {
        /// - Remark: Generated from `#/components/schemas/AccountProvider`.
        internal enum AccountProvider: String, Codable, Hashable, Sendable, CaseIterable {
            case kakao = "KAKAO"
        }
        /// 현재 인증된 Mosemo 계정의 공개 정보입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/AccountResponse`.
        internal struct AccountResponse: Codable, Hashable, Sendable {
            /// Mosemo 계정의 고유 식별자입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/accountId`.
            internal var accountId: Swift.String
            /// 계정이 생성된 시각입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/createdAt`.
            internal var createdAt: Foundation.Date
            /// 외부 인증 제공자를 통해 마지막으로 인증한 시각입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/lastAuthenticatedAt`.
            internal var lastAuthenticatedAt: Foundation.Date
            /// 계정 인증에 사용한 외부 인증 제공자입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/provider`.
            internal var provider: Components.Schemas.AccountProvider
            /// 날짜 조회에 사용하는 계정의 지원 시간대입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountResponse/timezone`.
            internal var timezone: Components.Schemas.Timezone
            /// Creates a new `AccountResponse`.
            ///
            /// - Parameters:
            ///   - accountId: Mosemo 계정의 고유 식별자입니다.
            ///   - createdAt: 계정이 생성된 시각입니다.
            ///   - lastAuthenticatedAt: 외부 인증 제공자를 통해 마지막으로 인증한 시각입니다.
            ///   - provider: 계정 인증에 사용한 외부 인증 제공자입니다.
            ///   - timezone: 날짜 조회에 사용하는 계정의 지원 시간대입니다.
            internal init(
                accountId: Swift.String,
                createdAt: Foundation.Date,
                lastAuthenticatedAt: Foundation.Date,
                provider: Components.Schemas.AccountProvider,
                timezone: Components.Schemas.Timezone
            ) {
                self.accountId = accountId
                self.createdAt = createdAt
                self.lastAuthenticatedAt = lastAuthenticatedAt
                self.provider = provider
                self.timezone = timezone
            }
            internal enum CodingKeys: String, CodingKey {
                case accountId
                case createdAt
                case lastAuthenticatedAt
                case provider
                case timezone
            }
        }
        /// Device 등록 결과입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/DeviceCreateResponse`.
        internal struct DeviceCreateResponse: Codable, Hashable, Sendable {
            /// 서버가 발급한 Device 식별자입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/DeviceCreateResponse/deviceId`.
            internal var deviceId: Swift.String
            /// Creates a new `DeviceCreateResponse`.
            ///
            /// - Parameters:
            ///   - deviceId: 서버가 발급한 Device 식별자입니다.
            internal init(deviceId: Swift.String) {
                self.deviceId = deviceId
            }
            internal enum CodingKeys: String, CodingKey {
                case deviceId
            }
        }
        /// 공개 오류 envelope 안의 공통 payload입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/ErrorPayload`.
        internal struct ErrorPayload: Codable, Hashable, Sendable {
            /// 실제 HTTP response status와 같은 오류 코드입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ErrorPayload/code`.
            internal var code: Swift.Int
            /// 검증 오류 상세 배열이며 일반 오류에서는 비어 있습니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ErrorPayload/details`.
            internal var details: [Components.Schemas.ValidationDetail]
            /// 개발자용 영문 오류 설명입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ErrorPayload/message`.
            internal var message: Swift.String
            /// 클라이언트가 분기할 애플리케이션 오류 식별자입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ErrorPayload/status`.
            internal var status: Swift.String
            /// Creates a new `ErrorPayload`.
            ///
            /// - Parameters:
            ///   - code: 실제 HTTP response status와 같은 오류 코드입니다.
            ///   - details: 검증 오류 상세 배열이며 일반 오류에서는 비어 있습니다.
            ///   - message: 개발자용 영문 오류 설명입니다.
            ///   - status: 클라이언트가 분기할 애플리케이션 오류 식별자입니다.
            internal init(
                code: Swift.Int,
                details: [Components.Schemas.ValidationDetail],
                message: Swift.String,
                status: Swift.String
            ) {
                self.code = code
                self.details = details
                self.message = message
                self.status = status
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case details
                case message
                case status
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Swift.Int.self,
                    forKey: .code
                )
                self.details = try container.decode(
                    [Components.Schemas.ValidationDetail].self,
                    forKey: .details
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                self.status = try container.decode(
                    Swift.String.self,
                    forKey: .status
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "details",
                    "message",
                    "status"
                ])
            }
        }
        /// Mosemo 공개 API가 반환하는 공통 오류 response입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/ErrorResponse`.
        internal struct ErrorResponse: Codable, Hashable, Sendable {
            /// 공개 오류 payload입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ErrorResponse/error`.
            internal var error: Components.Schemas.ErrorPayload
            /// Creates a new `ErrorResponse`.
            ///
            /// - Parameters:
            ///   - error: 공개 오류 payload입니다.
            internal init(error: Components.Schemas.ErrorPayload) {
                self.error = error
            }
            internal enum CodingKeys: String, CodingKey {
                case error
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.error = try container.decode(
                    Components.Schemas.ErrorPayload.self,
                    forKey: .error
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "error"
                ])
            }
        }
        /// IANA timezones accepted by the public API.
        ///
        /// - Remark: Generated from `#/components/schemas/Timezone`.
        internal enum Timezone: String, Codable, Hashable, Sendable, CaseIterable {
            case asiaSeoul = "Asia/Seoul"
            case americaNewYork = "America/New_York"
            case utc = "UTC"
        }
        /// 일회용 인증 코드를 Mosemo 액세스 토큰으로 교환하는 요청입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/TokenRequest`.
        internal struct TokenRequest: Codable, Hashable, Sendable {
            /// Kakao 로그인 callback에서 macOS 앱으로 전달한 일회용 인증 코드입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/code`.
            internal var code: Swift.String
            /// 로그인 요청의 code_challenge를 생성할 때 사용한 43~128자의 PKCE code verifier입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/codeVerifier`.
            internal var codeVerifier: Swift.String
            /// 토큰 발급 방식이며 authorization_code만 허용합니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/grantType`.
            internal enum GrantTypePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case authorizationCode = "authorization_code"
            }
            /// 토큰 발급 방식이며 authorization_code만 허용합니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenRequest/grantType`.
            internal var grantType: Components.Schemas.TokenRequest.GrantTypePayload
            /// Creates a new `TokenRequest`.
            ///
            /// - Parameters:
            ///   - code: Kakao 로그인 callback에서 macOS 앱으로 전달한 일회용 인증 코드입니다.
            ///   - codeVerifier: 로그인 요청의 code_challenge를 생성할 때 사용한 43~128자의 PKCE code verifier입니다.
            ///   - grantType: 토큰 발급 방식이며 authorization_code만 허용합니다.
            internal init(
                code: Swift.String,
                codeVerifier: Swift.String,
                grantType: Components.Schemas.TokenRequest.GrantTypePayload
            ) {
                self.code = code
                self.codeVerifier = codeVerifier
                self.grantType = grantType
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case codeVerifier
                case grantType
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Swift.String.self,
                    forKey: .code
                )
                self.codeVerifier = try container.decode(
                    Swift.String.self,
                    forKey: .codeVerifier
                )
                self.grantType = try container.decode(
                    Components.Schemas.TokenRequest.GrantTypePayload.self,
                    forKey: .grantType
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "codeVerifier",
                    "grantType"
                ])
            }
        }
        /// Mosemo API 인증에 사용하는 액세스 토큰 응답입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/TokenResponse`.
        internal struct TokenResponse: Codable, Hashable, Sendable {
            /// Authorization 헤더에 사용할 Mosemo 액세스 토큰입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/accessToken`.
            internal var accessToken: Swift.String
            /// 액세스 토큰이 발급 시점부터 유효한 시간(초)입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/expiresIn`.
            internal var expiresIn: Swift.Int
            /// 액세스 토큰의 인증 방식이며 Bearer로 고정됩니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/tokenType`.
            internal enum TokenTypePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case bearer = "Bearer"
            }
            /// 액세스 토큰의 인증 방식이며 Bearer로 고정됩니다.
            ///
            /// - Remark: Generated from `#/components/schemas/TokenResponse/tokenType`.
            internal var tokenType: Components.Schemas.TokenResponse.TokenTypePayload?
            /// Creates a new `TokenResponse`.
            ///
            /// - Parameters:
            ///   - accessToken: Authorization 헤더에 사용할 Mosemo 액세스 토큰입니다.
            ///   - expiresIn: 액세스 토큰이 발급 시점부터 유효한 시간(초)입니다.
            ///   - tokenType: 액세스 토큰의 인증 방식이며 Bearer로 고정됩니다.
            internal init(
                accessToken: Swift.String,
                expiresIn: Swift.Int,
                tokenType: Components.Schemas.TokenResponse.TokenTypePayload? = nil
            ) {
                self.accessToken = accessToken
                self.expiresIn = expiresIn
                self.tokenType = tokenType
            }
            internal enum CodingKeys: String, CodingKey {
                case accessToken
                case expiresIn
                case tokenType
            }
        }
        /// RequestValidationError에서 선택한 공개 검증 오류 정보입니다.
        ///
        /// - Remark: Generated from `#/components/schemas/ValidationDetail`.
        internal struct ValidationDetail: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ValidationDetail/LocPayload`.
            internal struct LocPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/ValidationDetail/LocPayload/value1`.
                internal var value1: Swift.String?
                /// - Remark: Generated from `#/components/schemas/ValidationDetail/LocPayload/value2`.
                internal var value2: Swift.Int?
                /// Creates a new `LocPayloadPayload`.
                ///
                /// - Parameters:
                ///   - value1:
                ///   - value2:
                internal init(
                    value1: Swift.String? = nil,
                    value2: Swift.Int? = nil
                ) {
                    self.value1 = value1
                    self.value2 = value2
                }
                internal init(from decoder: any Swift.Decoder) throws {
                    var errors: [any Swift.Error] = []
                    do {
                        self.value1 = try decoder.decodeFromSingleValueContainer()
                    } catch {
                        errors.append(error)
                    }
                    do {
                        self.value2 = try decoder.decodeFromSingleValueContainer()
                    } catch {
                        errors.append(error)
                    }
                    try Swift.DecodingError.verifyAtLeastOneSchemaIsNotNil(
                        [
                            self.value1,
                            self.value2
                        ],
                        type: Self.self,
                        codingPath: decoder.codingPath,
                        errors: errors
                    )
                }
                internal func encode(to encoder: any Swift.Encoder) throws {
                    try encoder.encodeFirstNonNilValueToSingleValueContainer([
                        self.value1,
                        self.value2
                    ])
                }
            }
            /// Pydantic validation error의 loc 원문입니다. JSON에서는 문자열과 정수 segment의 배열입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationDetail/loc`.
            internal typealias LocPayload = [Components.Schemas.ValidationDetail.LocPayloadPayload]
            /// Pydantic validation error의 loc 원문입니다. JSON에서는 문자열과 정수 segment의 배열입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationDetail/loc`.
            internal var loc: Components.Schemas.ValidationDetail.LocPayload
            /// Pydantic validation error의 msg 원문입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationDetail/msg`.
            internal var msg: Swift.String
            /// Pydantic validation error의 type 원문 또는 서버 정의 오류 유형입니다.
            ///
            /// - Remark: Generated from `#/components/schemas/ValidationDetail/type`.
            internal var _type: Swift.String
            /// Creates a new `ValidationDetail`.
            ///
            /// - Parameters:
            ///   - loc: Pydantic validation error의 loc 원문입니다. JSON에서는 문자열과 정수 segment의 배열입니다.
            ///   - msg: Pydantic validation error의 msg 원문입니다.
            ///   - _type: Pydantic validation error의 type 원문 또는 서버 정의 오류 유형입니다.
            internal init(
                loc: Components.Schemas.ValidationDetail.LocPayload,
                msg: Swift.String,
                _type: Swift.String
            ) {
                self.loc = loc
                self.msg = msg
                self._type = _type
            }
            internal enum CodingKeys: String, CodingKey {
                case loc
                case msg
                case _type = "type"
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.loc = try container.decode(
                    Components.Schemas.ValidationDetail.LocPayload.self,
                    forKey: .loc
                )
                self.msg = try container.decode(
                    Swift.String.self,
                    forKey: .msg
                )
                self._type = try container.decode(
                    Swift.String.self,
                    forKey: ._type
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "loc",
                    "msg",
                    "type"
                ])
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    internal enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    internal enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    internal enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    internal enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
internal enum Operations {
    /// 현재 계정 조회
    ///
    /// Bearer 액세스 토큰으로 인증된 Mosemo 계정 정보를 조회합니다.
    ///
    /// - Remark: HTTP `GET /api/v1/accounts/me`.
    /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)`.
    internal enum AccountsGetMe {
        internal static let id: Swift.String = "accountsGetMe"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/header`.
            internal struct Headers: Sendable, Hashable {
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AccountsGetMe.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                internal init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AccountsGetMe.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            internal var headers: Operations.AccountsGetMe.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            internal init(headers: Operations.AccountsGetMe.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.AccountResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.AccountResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AccountsGetMe.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.AccountsGetMe.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// 현재 인증된 계정의 공개 정보입니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.AccountsGetMe.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.AccountsGetMe.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/headers/WWW-Authenticate`.
                    internal enum WWWAuthenticatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case bearer = "Bearer"
                    }
                    /// 클라이언트가 사용해야 하는 인증 방식입니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/headers/WWW-Authenticate`.
                    internal var wwwAuthenticate: Operations.AccountsGetMe.Output.Unauthorized.Headers.WWWAuthenticatePayload?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - wwwAuthenticate: 클라이언트가 사용해야 하는 인증 방식입니다.
                    internal init(wwwAuthenticate: Operations.AccountsGetMe.Output.Unauthorized.Headers.WWWAuthenticatePayload? = nil) {
                        self.wwwAuthenticate = wwwAuthenticate
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.AccountsGetMe.Output.Unauthorized.Headers
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/401/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AccountsGetMe.Output.Unauthorized.Body
                /// Creates a new `Unauthorized`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.AccountsGetMe.Output.Unauthorized.Headers = .init(),
                    body: Operations.AccountsGetMe.Output.Unauthorized.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Unauthorized
            ///
            /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.AccountsGetMe.Output.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.AccountsGetMe.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            internal struct NotFound: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/404/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/404/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AccountsGetMe.Output.NotFound.Body
                /// Creates a new `NotFound`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.AccountsGetMe.Output.NotFound.Body) {
                    self.body = body
                }
            }
            /// Not Found
            ///
            /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.AccountsGetMe.Output.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            internal var notFound: Operations.AccountsGetMe.Output.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            internal struct MethodNotAllowed: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/405/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// 해당 route에서 허용되는 HTTP method 목록입니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/405/headers/Allow`.
                    internal var allow: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - allow: 해당 route에서 허용되는 HTTP method 목록입니다.
                    internal init(allow: Swift.String? = nil) {
                        self.allow = allow
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.AccountsGetMe.Output.MethodNotAllowed.Headers
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/405/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/405/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AccountsGetMe.Output.MethodNotAllowed.Body
                /// Creates a new `MethodNotAllowed`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.AccountsGetMe.Output.MethodNotAllowed.Headers = .init(),
                    body: Operations.AccountsGetMe.Output.MethodNotAllowed.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Method Not Allowed
            ///
            /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)/responses/405`.
            ///
            /// HTTP response code: `405 methodNotAllowed`.
            case methodNotAllowed(Operations.AccountsGetMe.Output.MethodNotAllowed)
            /// The associated value of the enum case if `self` is `.methodNotAllowed`.
            ///
            /// - Throws: An error if `self` is not `.methodNotAllowed`.
            /// - SeeAlso: `.methodNotAllowed`.
            internal var methodNotAllowed: Operations.AccountsGetMe.Output.MethodNotAllowed {
                get throws {
                    switch self {
                    case let .methodNotAllowed(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "methodNotAllowed",
                            response: self
                        )
                    }
                }
            }
            internal struct InternalServerError: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/500/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/accounts/me/GET/responses/500/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AccountsGetMe.Output.InternalServerError.Body
                /// Creates a new `InternalServerError`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.AccountsGetMe.Output.InternalServerError.Body) {
                    self.body = body
                }
            }
            /// Internal Server Error
            ///
            /// - Remark: Generated from `#/paths//api/v1/accounts/me/get(accountsGetMe)/responses/500`.
            ///
            /// HTTP response code: `500 internalServerError`.
            case internalServerError(Operations.AccountsGetMe.Output.InternalServerError)
            /// The associated value of the enum case if `self` is `.internalServerError`.
            ///
            /// - Throws: An error if `self` is not `.internalServerError`.
            /// - SeeAlso: `.internalServerError`.
            internal var internalServerError: Operations.AccountsGetMe.Output.InternalServerError {
                get throws {
                    switch self {
                    case let .internalServerError(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "internalServerError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 액세스 토큰 발급
    ///
    /// Kakao 로그인 callback에서 발급한 일회용 인증 코드와 PKCE code verifier를 검증한 뒤 Mosemo 액세스 토큰을 발급합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/auth/token`.
    /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)`.
    internal enum AuthExchangeToken {
        internal static let id: Swift.String = "authExchangeToken"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/header`.
            internal struct Headers: Sendable, Hashable {
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthExchangeToken.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                internal init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.AuthExchangeToken.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            internal var headers: Operations.AuthExchangeToken.Input.Headers
            /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.TokenRequest)
            }
            internal var body: Operations.AuthExchangeToken.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            internal init(
                headers: Operations.AuthExchangeToken.Input.Headers = .init(),
                body: Operations.AuthExchangeToken.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Cache-Control`.
                    internal enum CacheControlPayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case noStore = "no-store"
                    }
                    /// 응답을 저장하지 않도록 no-store로 설정됩니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Cache-Control`.
                    internal var cacheControl: Operations.AuthExchangeToken.Output.Ok.Headers.CacheControlPayload?
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Pragma`.
                    internal enum PragmaPayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case noCache = "no-cache"
                    }
                    /// 이전 HTTP 캐시와의 호환을 위해 no-cache로 설정됩니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/headers/Pragma`.
                    internal var pragma: Operations.AuthExchangeToken.Output.Ok.Headers.PragmaPayload?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - cacheControl: 응답을 저장하지 않도록 no-store로 설정됩니다.
                    ///   - pragma: 이전 HTTP 캐시와의 호환을 위해 no-cache로 설정됩니다.
                    internal init(
                        cacheControl: Operations.AuthExchangeToken.Output.Ok.Headers.CacheControlPayload? = nil,
                        pragma: Operations.AuthExchangeToken.Output.Ok.Headers.PragmaPayload? = nil
                    ) {
                        self.cacheControl = cacheControl
                        self.pragma = pragma
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.AuthExchangeToken.Output.Ok.Headers
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.TokenResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.TokenResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AuthExchangeToken.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.AuthExchangeToken.Output.Ok.Headers = .init(),
                    body: Operations.AuthExchangeToken.Output.Ok.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Mosemo Bearer 액세스 토큰입니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.AuthExchangeToken.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.AuthExchangeToken.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct BadRequest: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/400/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/400/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AuthExchangeToken.Output.BadRequest.Body
                /// Creates a new `BadRequest`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.AuthExchangeToken.Output.BadRequest.Body) {
                    self.body = body
                }
            }
            /// Bad Request
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Operations.AuthExchangeToken.Output.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            internal var badRequest: Operations.AuthExchangeToken.Output.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            internal struct NotFound: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/404/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/404/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AuthExchangeToken.Output.NotFound.Body
                /// Creates a new `NotFound`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.AuthExchangeToken.Output.NotFound.Body) {
                    self.body = body
                }
            }
            /// Not Found
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.AuthExchangeToken.Output.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            internal var notFound: Operations.AuthExchangeToken.Output.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            internal struct MethodNotAllowed: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/405/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// 해당 route에서 허용되는 HTTP method 목록입니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/405/headers/Allow`.
                    internal var allow: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - allow: 해당 route에서 허용되는 HTTP method 목록입니다.
                    internal init(allow: Swift.String? = nil) {
                        self.allow = allow
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.AuthExchangeToken.Output.MethodNotAllowed.Headers
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/405/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/405/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AuthExchangeToken.Output.MethodNotAllowed.Body
                /// Creates a new `MethodNotAllowed`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.AuthExchangeToken.Output.MethodNotAllowed.Headers = .init(),
                    body: Operations.AuthExchangeToken.Output.MethodNotAllowed.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Method Not Allowed
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)/responses/405`.
            ///
            /// HTTP response code: `405 methodNotAllowed`.
            case methodNotAllowed(Operations.AuthExchangeToken.Output.MethodNotAllowed)
            /// The associated value of the enum case if `self` is `.methodNotAllowed`.
            ///
            /// - Throws: An error if `self` is not `.methodNotAllowed`.
            /// - SeeAlso: `.methodNotAllowed`.
            internal var methodNotAllowed: Operations.AuthExchangeToken.Output.MethodNotAllowed {
                get throws {
                    switch self {
                    case let .methodNotAllowed(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "methodNotAllowed",
                            response: self
                        )
                    }
                }
            }
            internal struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/422/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AuthExchangeToken.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.AuthExchangeToken.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Unprocessable Content
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.AuthExchangeToken.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            internal var unprocessableContent: Operations.AuthExchangeToken.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            internal struct InternalServerError: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/500/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/auth/token/POST/responses/500/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.AuthExchangeToken.Output.InternalServerError.Body
                /// Creates a new `InternalServerError`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.AuthExchangeToken.Output.InternalServerError.Body) {
                    self.body = body
                }
            }
            /// Internal Server Error
            ///
            /// - Remark: Generated from `#/paths//api/v1/auth/token/post(authExchangeToken)/responses/500`.
            ///
            /// HTTP response code: `500 internalServerError`.
            case internalServerError(Operations.AuthExchangeToken.Output.InternalServerError)
            /// The associated value of the enum case if `self` is `.internalServerError`.
            ///
            /// - Throws: An error if `self` is not `.internalServerError`.
            /// - SeeAlso: `.internalServerError`.
            internal var internalServerError: Operations.AuthExchangeToken.Output.InternalServerError {
                get throws {
                    switch self {
                    case let .internalServerError(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "internalServerError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Device 등록
    ///
    /// 인증된 계정에 앱 설치를 Device로 등록하고 서버가 발급한 식별자를 반환합니다. 같은 계정과 Idempotency-Key의 재시도는 최초 식별자를 반환합니다.
    ///
    /// - Remark: HTTP `POST /api/v1/devices`.
    /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)`.
    internal enum DevicesCreate {
        internal static let id: Swift.String = "devicesCreate"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/devices/POST/header`.
            internal struct Headers: Sendable, Hashable {
                /// 하나의 Device 등록 시도를 식별하는 UUID입니다. 응답을 받기 전 재시도에는 같은 값을 사용합니다.
                ///
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/header/Idempotency-Key`.
                internal var idempotencyKey: Swift.String
                internal var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.DevicesCreate.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - idempotencyKey: 하나의 Device 등록 시도를 식별하는 UUID입니다. 응답을 받기 전 재시도에는 같은 값을 사용합니다.
                ///   - accept:
                internal init(
                    idempotencyKey: Swift.String,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.DevicesCreate.AcceptableContentType>] = .defaultValues()
                ) {
                    self.idempotencyKey = idempotencyKey
                    self.accept = accept
                }
            }
            internal var headers: Operations.DevicesCreate.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            internal init(headers: Operations.DevicesCreate.Input.Headers) {
                self.headers = headers
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Created: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/201/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/201/content/application\/json`.
                    case json(Components.Schemas.DeviceCreateResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.DeviceCreateResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.DevicesCreate.Output.Created.Body
                /// Creates a new `Created`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.DevicesCreate.Output.Created.Body) {
                    self.body = body
                }
            }
            /// 생성되었거나 동일한 재시도로 확인된 Device입니다.
            ///
            /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.DevicesCreate.Output.Created)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            internal var created: Operations.DevicesCreate.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/401/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/401/headers/WWW-Authenticate`.
                    internal enum WWWAuthenticatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case bearer = "Bearer"
                    }
                    /// 클라이언트가 사용해야 하는 인증 방식입니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/401/headers/WWW-Authenticate`.
                    internal var wwwAuthenticate: Operations.DevicesCreate.Output.Unauthorized.Headers.WWWAuthenticatePayload?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - wwwAuthenticate: 클라이언트가 사용해야 하는 인증 방식입니다.
                    internal init(wwwAuthenticate: Operations.DevicesCreate.Output.Unauthorized.Headers.WWWAuthenticatePayload? = nil) {
                        self.wwwAuthenticate = wwwAuthenticate
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.DevicesCreate.Output.Unauthorized.Headers
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/401/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/401/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.DevicesCreate.Output.Unauthorized.Body
                /// Creates a new `Unauthorized`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.DevicesCreate.Output.Unauthorized.Headers = .init(),
                    body: Operations.DevicesCreate.Output.Unauthorized.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Unauthorized
            ///
            /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.DevicesCreate.Output.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.DevicesCreate.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            internal struct NotFound: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/404/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/404/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.DevicesCreate.Output.NotFound.Body
                /// Creates a new `NotFound`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.DevicesCreate.Output.NotFound.Body) {
                    self.body = body
                }
            }
            /// Not Found
            ///
            /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.DevicesCreate.Output.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            internal var notFound: Operations.DevicesCreate.Output.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            internal struct MethodNotAllowed: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/405/headers`.
                internal struct Headers: Sendable, Hashable {
                    /// 해당 route에서 허용되는 HTTP method 목록입니다.
                    ///
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/405/headers/Allow`.
                    internal var allow: Swift.String?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - allow: 해당 route에서 허용되는 HTTP method 목록입니다.
                    internal init(allow: Swift.String? = nil) {
                        self.allow = allow
                    }
                }
                /// Received HTTP response headers
                internal var headers: Operations.DevicesCreate.Output.MethodNotAllowed.Headers
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/405/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/405/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.DevicesCreate.Output.MethodNotAllowed.Body
                /// Creates a new `MethodNotAllowed`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                internal init(
                    headers: Operations.DevicesCreate.Output.MethodNotAllowed.Headers = .init(),
                    body: Operations.DevicesCreate.Output.MethodNotAllowed.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Method Not Allowed
            ///
            /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)/responses/405`.
            ///
            /// HTTP response code: `405 methodNotAllowed`.
            case methodNotAllowed(Operations.DevicesCreate.Output.MethodNotAllowed)
            /// The associated value of the enum case if `self` is `.methodNotAllowed`.
            ///
            /// - Throws: An error if `self` is not `.methodNotAllowed`.
            /// - SeeAlso: `.methodNotAllowed`.
            internal var methodNotAllowed: Operations.DevicesCreate.Output.MethodNotAllowed {
                get throws {
                    switch self {
                    case let .methodNotAllowed(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "methodNotAllowed",
                            response: self
                        )
                    }
                }
            }
            internal struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/422/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.DevicesCreate.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.DevicesCreate.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Unprocessable Content
            ///
            /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.DevicesCreate.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            internal var unprocessableContent: Operations.DevicesCreate.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            internal struct InternalServerError: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/500/content`.
                internal enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/v1/devices/POST/responses/500/content/application\/json`.
                    case json(Components.Schemas.ErrorResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    internal var json: Components.Schemas.ErrorResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                internal var body: Operations.DevicesCreate.Output.InternalServerError.Body
                /// Creates a new `InternalServerError`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                internal init(body: Operations.DevicesCreate.Output.InternalServerError.Body) {
                    self.body = body
                }
            }
            /// Internal Server Error
            ///
            /// - Remark: Generated from `#/paths//api/v1/devices/post(devicesCreate)/responses/500`.
            ///
            /// HTTP response code: `500 internalServerError`.
            case internalServerError(Operations.DevicesCreate.Output.InternalServerError)
            /// The associated value of the enum case if `self` is `.internalServerError`.
            ///
            /// - Throws: An error if `self` is not `.internalServerError`.
            /// - SeeAlso: `.internalServerError`.
            internal var internalServerError: Operations.DevicesCreate.Output.InternalServerError {
                get throws {
                    switch self {
                    case let .internalServerError(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "internalServerError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        internal enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            internal init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            internal var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            internal static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
